export default function SupportTerms(){
  return (
    <section id="support" className="py-20 bg-slate-950">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid md:grid-cols-2 gap-6">
          <div id="terms" className="rounded-2xl border border-white/10 bg-white/5 p-6">
            <h3 className="text-white font-semibold text-xl mb-2">Terms & Conditions</h3>
            <p className="text-slate-300 text-sm">Use of Cognisphere is subject to fair usage and model provider policies. Aggregated responses are generated by third‑party LLMs and may contain errors. Do not use for medical, legal, or financial advice without human review.</p>
          </div>
          <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
            <h3 className="text-white font-semibold text-xl mb-2">Support</h3>
            <p className="text-slate-300 text-sm">Have questions or need help? Reach us at support@cognisphere.ai. Enterprise SLAs available on request.</p>
          </div>
        </div>
      </div>
    </section>
  )
}
